### ISSUE TITLE
Waystone not connected

### ISSUE THREAD

**Issue by nomadjimbob** [Drustcraft/denizen#117]
### Describe the bug

When a waystone is searching for a destination it will typically fail if there are no chunks loaded within the maximum range. Flagged blocks require the chunk to also be loaded.

The method is required to be changed to instead store the data in a list instead of flagged blocks so it is always available regardless of a chunks status

**Comment by ProjectHSI** [comment]
There is a command for chunk loading, I'll see if I can monitor waystone placement.
https://meta.denizenscript.com/Docs/Commands/chunkload

**Comment by nomadjimbob** [comment]
Yeah I'm aware of that command, however we would need to record the placed locations in a world flag so they are always available (guilds save in world flags as well).

If we are storing the data in a world flag, then there is not really any need to do a chunk load as we could store the location and the block material name underneath the lodestone in the flag and do a TP to the closest (TP does not require a chunk load as it does it internally)

**Comment by ProjectHSI** [comment]
ok

**Comment by nomadjimbob** [comment]
fixed in commit 5c9142db98fc4e357b996700f05fc9e0fb03968a
