### ISSUE TITLE
Decay Timeout

### ISSUE THREAD

**Issue by ProjectHSI** [Drustcraft/denizen#125]
### What feature do you want to see added?

To prevent houses from being destroyed, only register players that have been in the chunk for something like 120 seconds.

**Comment by nomadjimbob** [comment]
This feature already exists, however, is named /server/regenerate. Maybe we should rename it to decay under 2.1?

**Comment by ProjectHSI** [comment]
possibly, although I am aware of it, however I am suggesting to add to it where they must stay in the chunk for a certain amount of time to pervent decay.

**Comment by nomadjimbob** [comment]
The regenerate feature already does this.

By default, every hour there is a 2% chance a block will be reverted back to its original block if the chunk has not been visited by a player in 28 days.

So if you don't visit a chunk in 28 days, every hour it will start to decay. If you visit it after the decay has started, it will not start decaying again until another 28 days have passed

**Comment by ProjectHSI** [comment]
I'm not sure if you're missing the point here, this is to prevent chunks that aren't _occupied_ in the sense that players aren't living in them, if you just go to a chunk to immediately leave. I don't think the chunk shouldn't decay.

**Comment by nomadjimbob** [comment]
I understand now, but this option contradicts your original message.

> To prevent houses from being destroyed, only register players that have been in the chunk for something like 120 seconds.

If we only update the `last_inhabited` time of a chunk after the player stays within the chunk for a period of time (say 120s), then a player who simply walks through a chunk would not stop the house from being destroyed. Currently, it does.

**Comment by nomadjimbob** [comment]
Just so we are both on the same page:

Day 1 - Chunk A is a nice flat grassy plain
Day 2 - nomadjimbob builds a house on the chunk and logs out. Decay countdown starts on Chunk A (runs on Day 30)
Day 5 - nomadjimbob logs in at Chunk A and walks off. Decay countdown resets on Chunk A (now runs on Day 33)
Day 30 - project_hsi stumbles across nomadjimbobs house. Decay countdown resets on Chunk A (now runs on Day 58)
Day 58 - no one has visited Chunk A in 28 days, decay runs hourly
Day 59 - project_hsi on his way back walks through Chunk A and decay is visible on the house. project takes all the grass blocks! Decay countdown resets on Chunk A (now runs on Day 87)
Day 87 - Decay on Chunk A starts again
Day ~102 - Chunk A has now finally revert back to the original flat grassy plain with the house gone and all the grass blocks that project_hsi took put back

**Comment by ProjectHSI** [comment]
alright.

also it appears I made a mistake, whoops! I meant to say _if the player isn't living in the chunk (or surrounding chunks) then the house should still be destroyed by decay, even if a player has walking into the chunk. this is supposed to prevent players from walking into a chunk, and then immediately leaving because they were either walked into the chunk to travel or simply explored the house for a short time._

however, based on the reply 2 replies above, perhaps a _pause_ system would be work, while the player is in the chunk, decay wouldn't happen, **however** the last_inhabited flag would **not be reset**, when a player is in the chunk for something like 2 minutes. It **is** reset

**Comment by nomadjimbob** [comment]
The downside to this (apart from the extra calculations we would need to do eating valuable ticks) is you would need to spent at least 2 mins in each chunk of your base every 28 days to not have decay (instead of just walking around the base).

Maybe we should reduce the decay starting time from 28 days to 14 days and lower the block chance of change from 2% to 1%?
